-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgTiIuspYseV7WoVwX
KKcHQ7VfKdMasojj6Dd8Ur+aUxmgCgYIKoZIzj0DAQehRANCAASXW+2LNOxtyXYS
lzH8eOKXw1QUGuhnspr7mT4xqCBqcXaTar8vg6OxioPpPY0NTzpdp/BfWq23tCMF
jDmbfxYi
-----END PRIVATE KEY-----